/*
 * Spring Boot中使用Swagger2构建RESTful APIs
 * 更多Spring Boot相关文章请关注：http://blog.didispace.com/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseListUser;
import io.swagger.client.model.ResponseUser;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsercontrollerApi
 */
public class UsercontrollerApiTest {

    private final UsercontrollerApi api = new UsercontrollerApi();

    
    /**
     * 获取用户列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserListUsingGETTest() throws ApiException {
         ResponseListUser response = api.getUserListUsingGET();
         System.out.println("======================" + response);
        // TODO: test validations
    }
    
    /**
     * 获取用户详细信息
     *
     * 根据url的id来获取用户详细信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() throws ApiException {
        String id = "1";
         ResponseUser response = api.getUserUsingGET(id);
        System.out.println("======================" + response);
        // TODO: test validations
    }
    
}
